nasajon_calendario_homepage:
    pattern:  /
    defaults: { _controller: NasajonCalendarioBundle:Default:index }

nasajon_calendario_login:
    pattern:  /login
    defaults: { _controller: NasajonCalendarioBundle:Login:index }

nasajon_calendario_logout:
    pattern:  /logout
    defaults: { _controller: NasajonCalendarioBundle:Login:logout }

