parameters:
#    nasajon_calendario.example.class: Nasajon\CalendarioBundle\Example

services:
#    nasajon_calendario.example:
#        class: %nasajon_calendario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
